### ISSUE TITLE
Design UX

### ISSUE THREAD

**Issue by Ssisakhti** [sepidario/yadetam-android#1]
- [ ] match maker page: start new connection or enter partner's code

- [ ] sender page: choose and send stickers

- [ ] notification view

**Comment by Ssisakhti** [comment]
![wireframe v_2 0](https://user-images.githubusercontent.com/3183983/42744495-35576db0-88e2-11e8-9120-ff6ca63be7aa.png)

@Alifazaeli 
علی جان نظرت چیه؟
اون تصویر آدم‌ها مثلن ایموجی هستند البته

**Comment by Alifazaeli** [comment]
@Ssisakhti به نظر من اوکیه همین

**Comment by Ssisakhti** [comment]
پیشنهادم اینه که برای ارسال ایموجی‌ها LongClick اتفاق بیفته. که اشتباهی ارسال نشه با دست خوردن و از طرفی تایید هم نخواد
@Alifazaeli

**Comment by Ssisakhti** [comment]
۱. صفحه سوم حذف شود. و صفحه دوم و سوم اضافه شود

**Comment by Ssisakhti** [comment]
![wireframe v_3 0](https://user-images.githubusercontent.com/3183983/43126375-c8702078-8f41-11e8-9749-3d8c804d9ab1.png)
